#!/bin/sh

# ^c$var^ = fg color
# ^b$var^ = bg color

interval=0

# load colors
. ~/.config/dwm/bar_themes/catppuccin

cpu() {
  cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)

  printf "^c$black^ ^b$green^ CPU"
  printf "^c$white^ ^b$grey^ $cpu_val"
}

pkg_updates() {
  #updates=$({ timeout 20 doas xbps-install -un 2>/dev/null || true; } | wc -l) # void
  updates=$({ timeout 20 checkupdates 2>/dev/null || true; } | wc -l) # arch
  # updates=$({ timeout 20 aptitude search '~U' 2>/dev/null || true; } | wc -l)  # apt (ubuntu, debian etc)

  if [ -z "$updates" ]; then
    printf "^c$green^ Fully Updated"
  else
    printf "^c$green^ $updates"" updates"
  fi
}

battery() {
    local get_capacity="$(cat /sys/class/power_supply/*/capacity)"
    local charging_emojis=(" " " " " " " ")
    local charging_emoji_index=$((get_capacity / 25))
    local low_battery_notification_file="/tmp/low_battery_notification"

    if [[ charging_emoji_index -gt 3 ]]; then
        charging_emoji_index=3
    fi

    local charging_emoji="${charging_emojis[$charging_emoji_index]}"

    printf "%s" "^c$blue^ $charging_emoji $get_capacity%"
}




brightness() {
  brightness_val="$(brillo | cut -d . -f1)"
  brightness_emojis=("" "󰃛" " " "󰃚 ")
  brightness_emoji_index=$((brightness_val / 25))

  if [[ brightness_emoji_index -gt 3 ]]; then
    brightness_emoji_index=3
  fi

  brightness_emoji="${brightness_emojis[$brightness_emoji_index]}"

  printf "^c$black^ ^b$red^ $brightness_emoji "
  printf "%s" "^c$red^^b$black^ $brightness_val%"

}

mem() {
  printf "^c$blue^^b$black^  "
  printf "^c$blue^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

wlan() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	up) printf "^c$black^ ^b$blue^   ^d^%s" " ^c$blue^Connected" ;;
	down) printf "^c$black^ ^b$blue^ 睊 ^d^%s" " ^c$blue^Disconnected" ;;
	esac
}

clock() {
	printf "^c$black^ ^b$darkblue^  "
	printf "^c$black^^b$blue^ $(date '+%H:%M') "
}

volume() {
    local volume_val=$(pactl list sinks | grep '^[[:space:]]Volume:' | awk '{gsub(/[\[\]%]/, "", $5); print $5}')
    local icon=""

    if [ "$volume_val" -eq 0 ]; then
        icon="󰝛 "  # Icon for mute
    elif [ "$volume_val" -lt 50 ]; then
        icon=""  # Icon for middle volume
    else
        icon=""  # Icon for full volume
    fi

    printf "^c$black^ ^b$blue^ $icon"
    printf "%s" "^c$white^ ^b$grey^ $volume_val%"
}



while true; do

  [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name " $updates $(brightness) $(mem) $(volume) $(battery)  $(cpu) $(wlan) $(clock)"
done
