#!/usr/bin/env sh
# Copyright PwnWriter // METIS Linux 2022 - present

# Global variable to generate random number
ssname=$(date +%N | sed 's/...$//').png

# Poweroff selection menu
poweroff_menu() {
  selected=$(printf "%s\n" "cancel" "shutdown" "reboot" "sleep" | dmenu -c)
  case "$selected" in
    "shutdown")
      doas poweroff
      ;;
    "reboot")
      doas reboot
      ;;
    "sleep")
      doas zzz
      ;;
    "cancel")
      return
      ;;
  esac
}

# Check the directory to save screenshots. Create one if not found.
check_ssdir() {
  if [ ! -d "$HOME/pix/ss/" ]; then
    mkdir -p "$HOME/pix/ss"
  fi
}

# Take a screenshot using ImageMagick without selection menu
ss_without_selection() {
  check_ssdir
  import -window root "$HOME/pix/ss/$ssname"
  xclip -selection clipboard -t image/png -i "$HOME/pix/ss/$ssname"
  notify-send  -i "$HOME/pix/ss/$ssname" "Screenshot taken" "Screenshot image copied to clipboard"
}

# Take a screenshot using ImageMagick with selection menu
ss_with_selection() {
  check_ssdir
  import "$HOME/pix/ss/$ssname"
  xclip -selection clipboard -t image/png -i "$HOME/pix/ss/$ssname"
  notify-send -i "$HOME/pix/ss/$ssname" "Screenshot taken" "Screenshot image copied to clipboard"
}

# Search in a browser directly through dmenu
search() {
  URL='https://duckduckgo.com/?q='
  query=$(echo '' | dmenu -p "Search:")
  if [ -n "$query" ]; then
    xdg-open "${URL}${query}" 2> /dev/null
  fi
}

# Function to handle the quick links
handle_quicklinks() {
  declare -a names=()
  declare -a urls=()
  while IFS=, read -r name url; do
    names+=("$name")
    urls+=("$url")
  done < ~/.config/dwm/quicklinks.csv

  # Build the menu options
  menu_options=""
  for name in "${names[@]}"; do
    menu_options+="$name\n"
  done

  choice=$(echo -e "$menu_options" | sort -u | dmenu -c -i -l 10 -nb "$bg" -nf "$fg" -sb "$altbg" -sf "$fg" -fn "$FONT" -p 'Quick Links:')

  for i in "${!names[@]}"; do
    if [[ "${names[$i]}" == "$choice" ]]; then
      url="${urls[$i]}"
      break
    fi
  done

  if [ -n "$url" ]; then
    xdg-open "https://$url"
  else
    echo "Exiting..."; exit 1
  fi
}

#  increase volume
increase_volume() {
        pactl set-sink-volume @DEFAULT_SINK@ +5%
}

# decrease volume
decrease_volume() {
        pactl set-sink-volume @DEFAULT_SINK@ -5%
}

# mute/unmute volume
toggle_mute() {
        local icon_dir="/usr/share/icons/dwm/dunst"
        pactl set-sink-mute @DEFAULT_SINK@ toggle 
}

# getopt implementation for arguments
while getopts 'sbpwqvudm' option; do
  case "$option" in
    s)
      ss_with_selection
      ;;
    b)
      ss_without_selection
      ;;
    p)
      poweroff_menu
      ;;
    w)
      search
      ;;
    q)
      handle_quicklinks
      ;;
    u)
      increase_volume
      ;;
    d)
      decrease_volume
      ;;
    m)
      toggle_mute
      ;;
    *)
      exit 1
      ;;
  esac
done

